# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Tpircs Blog
tagline:             'Just try harder'
description:         'Blog of Tpircs, a stupid programmer'
url:                 http://blog.tpircsboy.com
baseurl:             ''
paginate:            5
gems: ["jekyll-paginate"]

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
